//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFinancieros_Facturas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasXml
    {
        public int id { get; set; }
        public string Folio { get; set; }
        public string EmisorNombre { get; set; }
        public string ReceptorNombre { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    }
}
