//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFinancieros_Facturas.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbFacturasFinancierosEntities : DbContext
    {
        public dbFacturasFinancierosEntities()
            : base("name=dbFacturasFinancierosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<tcareas> tcareas { get; set; }
        public DbSet<tctipogasto> tctipogasto { get; set; }
        public DbSet<tdfacturasGrupo> tdfacturasGrupo { get; set; }
        public DbSet<tdoprev> tdoprev { get; set; }
        public DbSet<tcproovedor_bloqueado> tcproovedor_bloqueado { get; set; }
        public DbSet<tcpartida> tcpartida { get; set; }
        public DbSet<tcpartida_anio> tcpartida_anio { get; set; }
        public DbSet<tctercero_institucional> tctercero_institucional { get; set; }
        public DbSet<tcusuarios> tcusuarios { get; set; }
        public DbSet<tdfacturas> tdfacturas { get; set; }
    
        public virtual ObjectResult<sel_facturas_fecha_Result> sel_facturas_fecha(Nullable<System.DateTime> fechai, Nullable<System.DateTime> fechaf)
        {
            var fechaiParameter = fechai.HasValue ?
                new ObjectParameter("fechai", fechai) :
                new ObjectParameter("fechai", typeof(System.DateTime));
    
            var fechafParameter = fechaf.HasValue ?
                new ObjectParameter("fechaf", fechaf) :
                new ObjectParameter("fechaf", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_facturas_fecha_Result>("sel_facturas_fecha", fechaiParameter, fechafParameter);
        }
    }
}
