//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFinancieros_Facturas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosSiafev
    {
        public int Id { get; set; }
        public string SectorDependencia { get; set; }
        public string Beneficiario { get; set; }
        public string NumeroBeneficiario { get; set; }
        public string Folio { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Pagado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string ReferenciaPago { get; set; }
        public string FuenteFtto { get; set; }
        public string DescripcionFuente { get; set; }
        public string OC { get; set; }
        public string ClasificacionProveedor { get; set; }
        public string Sector { get; set; }
        public string DescripcionSector { get; set; }
        public string TipoGasto { get; set; }
        public string CuentaCargo { get; set; }
        public string BancoCargo { get; set; }
        public string CuentaAbono { get; set; }
        public string BancoAbono { get; set; }
        public System.DateTime FechaImportacion { get; set; }
        public string UsuarioImportacion { get; set; }
    }
}
