//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFinancieros_Facturas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcpartida
    {
        public int idtcpartida { get; set; }
        public string clave_partida { get; set; }
        public string partida { get; set; }
        public int idtcpartida_anio { get; set; }
    
        public virtual tcpartida_anio tcpartida_anio { get; set; }
    }
}
