//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFinancieros_Facturas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcpartida_anio
    {
        public tcpartida_anio()
        {
            this.tcpartida = new HashSet<tcpartida>();
        }
    
        public int idtcpartida_anio { get; set; }
        public int anio { get; set; }
    
        public virtual ICollection<tcpartida> tcpartida { get; set; }
    }
}
