//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFinancieros_Facturas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcproovedor_bloqueado
    {
        public int idproovedor { get; set; }
        public string rfc_proovedor { get; set; }
        public string proovedor { get; set; }
        public System.DateTime dt_tcproovedor_bloqueado { get; set; }
    }
}
