//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFinancieros_Facturas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tctercero_institucional
    {
        public int idtcterceros_institucional { get; set; }
        public string nombre_tercero { get; set; }
    }
}
