//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFinancieros_Facturas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdfacturas
    {
        public int Id { get; set; }
        public string Folio { get; set; }
        public string Estado { get; set; }
        public decimal Importe { get; set; }
        public string Rfce { get; set; }
        public string Rsemisor { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaCertifica { get; set; }
        public string PacCertifico { get; set; }
        public int Idarea { get; set; }
        public Nullable<int> IdPago { get; set; }
        public Nullable<int> idtctipo_pago { get; set; }
        public string NoOdp { get; set; }
        public string FolioInternoFactura { get; set; }
        public string ConceptoDevol { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public Nullable<System.DateTime> FechaDevol { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string Estreg { get; set; }
        public Nullable<System.DateTime> FechaReingreso { get; set; }
        public string Revisor { get; set; }
        public string Capturista { get; set; }
        public Nullable<int> Egreso { get; set; }
        public Nullable<int> Idconcepto { get; set; }
        public Nullable<int> FolioSujeto { get; set; }
        public string Validador { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> idtcpartida { get; set; }
        public Nullable<int> idtcterceros_institucional { get; set; }
        public Nullable<int> idtc_contrato { get; set; }
        public Nullable<System.DateTime> FechaVentanilla { get; set; }
    
        public virtual tcContrato tcContrato { get; set; }
        public virtual tcpartida tcpartida { get; set; }
        public virtual tctercero_institucional tctercero_institucional { get; set; }
    }
}
